# Generated by Django 2.2 on 2020-05-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_name', models.CharField(max_length=20, unique=True)),
                ('webinar_created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('for_everybody', models.BooleanField(default=True)),
                ('students', models.ManyToManyField(related_name='students_to_webinars', through='webinars.join', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20)),
                ('session_created_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('webinar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webinars.Webinar')),
            ],
        ),
        migrations.AddField(
            model_name='join',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.Webinar'),
        ),
    ]
