# Generated by Django 2.2 on 2020-05-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('yt_link_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.Session')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text_block_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.Session')),
            ],
        ),
        migrations.CreateModel(
            name='gdlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gd_link_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.Session')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.Session')),
            ],
        ),
    ]
